# https://github.com/openai/gym

environment:
  type: "GymContinuous"
  name: "HopperPyBulletEnv-v0"
  frame_skip: 1
  last_action_to_obs: False
  last_reward_to_obs: False
  obs_stacks: 1
  reset_params:
    start-seed: 0
    num-seeds: 100

model:
  load_model: False
  model_path: ""
  checkpoint_interval: 25
  activation: "tanh"
  vis_encoder: "cnn"
  vec_encoder: "linear"
  num_vec_encoder_units: 128
  hidden_layer: "default"
  num_hidden_layers: 1
  num_hidden_units: 128
  num_hidden_pre_head: 128
  share_parameters: False
  tanh_squashing: True
  normalize_observations: True

evaluation:
  evaluate: False
  n_workers: 3
  seeds: [1001, 1002, 1003, 1004, 1005]
  interval: 50

sampler:
  type: "TrajectorySampler"
  n_workers: 8
  worker_steps: 2048

trainer:
  algorithm: "PPO"
  resume_at: 0
  gamma: 0.99
  lamda: 0.95
  updates: 489
  epochs: 10
  refresh_buffer_epoch: -1
  n_mini_batches: 32
  value_coefficient: 0.5
  max_grad_norm: 0.5
  share_parameters: True
  learning_rate_schedule:
    initial: 3.0e-4
    final: 3.0e-4
    power: 1.0
    max_decay_steps: 50
  beta_schedule:
    initial: 0
    final: 0
    power: 1.0
    max_decay_steps: 50
  clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 50
